### PR TITLE
Developer

### PR DESCRIPTION
**Pull request by TashfeenRao**

### CODE REVIEW

**Comment by shshamim63** [comment]
## :point_right:  Changes Required :point_left: 
___

Hi @TashfeenRao  and @mekinus ,
Good initiative :clap: , But to complete this project you need to cover some issues mentioned below :point_down: .

___

## [Mandatory Changes]
1. On the actual webpage it consists separated intuit logo, (mint logo, turbotax and quickbooks logo with their name.). But I can see that you tried to cover that section by using an image. It should be something like this.
mint
##### Please fix this issue.
2. Your form elements are broken, kindly fix their flow and maintain the alignment as in the original webpage.
mint1
3. Form footer section needs to be modified.
##### -> yours one 
mint2
##### -> Actual one 
actual
___

### Please fix the above issues :point_up: and send another review request. :pray: 

## Happy Coding :clubs: 
### <em> Shakhawat Hossain </em>
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/) | [Slack](Shakhawat Hossain)

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Nice job implementing that other change. The form looks much better now. However, there is one more problem to fix. We are so sorry for not pointing this out earlier on.

https://github.com/TashfeenRao/mint-forms/blob/1d3a3683b8a1830ea3037916e5ff5cdd24ea9376/index.html#L33-L49

From the above code, you used `<input type='text'...` for all your inputs. You should always use the right attributes for your `<input>` tags. Refer to [this MDN article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#%3Cinput%3E_types) for further explanations and list of types  and select the right types for `email, phone and password`

**Kindly submit another code review request after fixing the issue**


Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by Anna-Myzukina** [comment]
# Project Approved image

### Congratulations! You've done a fantastic job  image  image

##### Friendly advice add property font-style: italic; to .small-font

               .small-font {
                      font-size: 1rem;
                      line-height: normal;
                     font-family: "Roboto", sans-serif;
                     font-style: italic;
                   }

##### And this property  color: #0984e3;  to .sign-link

                  .sign-link {
                             text-decoration: none;
                            font-family: "Roboto", sans-serif;
                            color: #0984e3;
                          }

##### And the last but not least: 
remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). Hope in the next project you can do this image




### You DON'T need to request for another review and can merge to master now. Good luck with your next project!!!

**Review by Anna-Myzukina — APPROVED** [review]
# Project Approved image

### Congratulations! You've done a fantastic job  image  image

##### Friendly advice add property font-style: italic; to .small-font

               .small-font {
                      font-size: 1rem;
                      line-height: normal;
                     font-family: "Roboto", sans-serif;
                     font-style: italic;
                   }

##### And this property  color: #0984e3;  to .sign-link

                  .sign-link {
                             text-decoration: none;
                            font-family: "Roboto", sans-serif;
                            color: #0984e3;
                          }

##### And the last but not least: 
remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). Hope in the next project you can do this image




### You DON'T need to request for another review and can merge to master now. Good luck with your next project!!!

**Pull request merged**
